### ISSUE TITLE
lintによる指摘事項を減らす

### ISSUE THREAD

**Issue by massongit** [nakkaa/hato-bot#101]
lintでの指摘事項を修正する or ignoreすることで、lintによる指摘事項を減らします。

**Comment by Goryudyuma** [comment]
全部やったかな？

**Comment by massongit** [comment]
https://github.com/nakkaa/hato-bot/pull/129#issuecomment-640013771
残りの指摘事項

**Comment by Goryudyuma** [comment]
おわり
