### ISSUE TITLE
developブランチへのマージは誰かのレビューがあれば良い

### ISSUE THREAD

**Issue by Goryudyuma** [nakkaa/hato-bot#128]
なっかあちゃんの負荷低減のため
developへのマージは誰か一人以上のレビューが必要
developからmasterへのマージはなっかあちゃんのレビューが必要

こんな感じで負荷減らせて、いい感じに回せるんじゃない？

**Comment by nakkaa** [comment]
書いた

https://github.com/nakkaa/hato-bot/wiki/開発ルール

**Comment by Goryudyuma** [comment]
あり！
