### ISSUE TITLE
pipとして導入可能にする

### ISSUE THREAD

**Issue by fono09** [nakkaa/hato-bot#167]
https://github.com/nakkaa/sudden-death

これをpipで入れられるように整備してsubmodule追従をやめる

**Comment by Goryudyuma** [comment]
sudden-deathの方にもIssue建てられるよ(今はここでしか使ってないからそれでもいい気がするけど)

**Comment by fono09** [comment]
一旦ここに集約して、pipとして独立してメンテできるようになったらそっちに移す

**Comment by massongit** [comment]
関連Issue: https://github.com/nakkaa/sudden-death/issues/11

**Comment by fono09** [comment]
#170 で完了
