### ISSUE TITLE
Lint入れた結果、今のコードは指摘点がたくさんある

### ISSUE THREAD

**Issue by Goryudyuma** [nakkaa/hato-bot#54]
全部直すか、Lintのルールを書き換えて無視するなどの対応が必要。
どこまでコーディング規約を守るか？

**Comment by nakkaa** [comment]
新規開発はなるべくLintを踏襲するようにして既存機能については
改修が必要な箇所だけ直す感じがいいかなと思っている。

**Comment by nakkaa** [comment]
#56 がマージされたら、対応済みになりそう。
