### ISSUE TITLE
pythonコードを含まないコミットについてはCIでLintしない

### ISSUE THREAD

**Issue by massongit** [nakkaa/hato-bot#68]
pythonコードを含まないコミットをCIでLintすると、Lintのhelpが出てきてしまうので、Lintしない 
(もしくは結果を出力しない) ようにします。

Lintのhelpが出てきてしまう例: https://github.com/nakkaa/hato-bot/pull/67#issuecomment-632695973

**Comment by nakkaa** [comment]
@massongit please close this ticket.
