### ISSUE TITLE
create_env.pyをsqlにする

### ISSUE THREAD

**Issue by massongit** [nakkaa/hato-bot#99]
https://github.com/nakkaa/hato-bot/blob/develop/create_env.py はSQLを実行しているだけなので、必要なSQLをファイルとして置いておけば、それを実行できるようにします。

**Comment by massongit** [comment]
https://github.com/nakkaa/hato-bot/issues/100 を行うついでにやれば実現できるはず。

**Comment by Goryudyuma** [comment]
かなり前にやったのでclose
